# Exersice 5.A Numoy Fundamentals
This notebook covers the basics of NumPy arrays including creation, data types, dimensions, slicing, and transposing.

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = ['apple', 'banana', 'cherry', 'date']

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [6]:
print(arr_1.dtype)
# U6 means Unicode string, max 6 characters long

<U6


In [9]:
arr_2 = np.array([(10, 11, 12), (13, 14, 15)])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [11]:
print(arr_2.T)
# This flips rows and columns

[[10 13]
 [11 14]
 [12 15]]


In [14]:
print(arr_2)
# arr_2 is unchanged. T creates a new view, it does not modify the original

[[10 11 12]
 [13 14 15]]


In [15]:
arr_3 = np.array([(1, 3, 5), (2, 4, 6)])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [17]:
arr_4 = np.array([arr_3[0, 2], arr_3[1, 1]])
print(arr_4)
#arr_3[0,2] = row 0, column 2 = 5
#arr_3[1,1] = row 1, column 1 = 4
#so arr_4 = [5,4]

[5 4]


In [18]:
arr_5 = np.ones((2, 2, 2))
print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
