# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])

In [3]:
print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In [6]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


The first loop multiplies each row by 2, returning arrays.
The second loop multiplies each individual element by 2 usnig a nested loop, returning single numbers.

In [7]:
for x in arrA:
    for y in x:
        loop_result = x * 2
        print(loop_result)
#loop_result miltiplies the whole row x by 2, not just y so even though we loop through each element with y
#prints entire row 3 times.


[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Join and Stacking Arrays

In [9]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [10]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [14]:
stacked_array_1 =np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [17]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)

#ValueError: all input arrays must have the same shape. joined_array_1 has 4 rows but arrA has 2 rows

ValueError: all input arrays must have the same shape

In [19]:
h = np.hstack((arrA, arrA))
print(h)
#hstack horizontally - same as axis=1, adds columns

v = np.vstack((arrA, arrA))
print(v)
#vstack stacks vertically - same as axis=0, adds rows

d = np.dstack((arrA, arrA))
print(d)
#dstack stacks depth-wise - adds a third dimension

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [21]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
#Result: 2 arrays, each with 2 rows and 3 columns(2D)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [25]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
#Result: 3 arrays - first two have 2 rows, last has 0 rows (2D each)

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and Replacing Array Values

In [26]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)
# % 2 == 0 checks if number is even
# if even: keep the vlaue from arrA
#if odd: replace with 'odd'

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [30]:
arrB = np.array([(7, 6), (13, 5), (7, 3)])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)
#sorts each row from smallest to largest

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [32]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)
#z is a boolean array - True where value < 7, False otherwise
#arrC contains only values where z is True

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [34]:
y = arrB >= 7
arrD = arrB[y]
print(arrD)
# y is True where value >= 7
# arrD contains only those values

[ 7 13  7]
