# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

In [4]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

## Permutations

In [5]:
print(r_4)

[[63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]
 [50 76 39 71 71]]


In [6]:
np.random.shuffle(r_4)
print(r_4)

[[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]]


The shuffle function rearranged the rows of r_4 but kept the values within each row in the same order. It modifies the original
array directly.

In [10]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[49 66 56 62 34]
 [50 76 39 71 71]
 [50 35 62 20 38]
 [63 41 79 43 62]]
[[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]]


Use shuffle when you want to modify the original array in place.
Use permutation when you want a shuffled copy but need the original.

## Mathematical Operations

In [11]:
print(f"r_1: {r_1}, shape: {r_1.shape}")
print(f"r_2: {r_2}, shape: {r_2.shape}")
result = np.add(r_1, r_2)
print(f"result: {result}, shape: {result.shape}")

r_1: [ 6 12], shape: (2,)
r_2: [[ 9 15]], shape: (1, 2)
result: [[15 27]], shape: (1, 2)


In [18]:
print(f"r_1: {r_1}, shape: {r_1.shape}")
print(f"r_3: {r_3}, shape: {r_3.shape}")
result2 = np.add(r_1, r_3)
print(f"result: {result2}, shape: {result2.shape}")

r_1: [ 6 12], shape: (2,)
r_3: [[0.2630867 ]
 [0.61323603]], shape: (2, 1)
result: [[ 6.2630867  12.2630867 ]
 [ 6.61323603 12.61323603]], shape: (2, 2)


In [19]:
print(f"r_2: {r_2}, shape: {r_2.shape}")
print(f"r_4: {r_4}, shape: {r_4.shape}")
result3 = np.add(r_2, r_4)
print(f"result: {result3}, shape: {result3.shape}")

r_2: [[ 9 15]], shape: (1, 2)
r_4: [[50 76 39 71 71]
 [63 41 79 43 62]
 [50 35 62 20 38]
 [49 66 56 62 34]], shape: (4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

In [20]:
try:
    print(np.add(r_1, r_4))
except ValueError as e:
    print(f"r_1 + r_4 error: {e}")
# r_1 is hsape (2,) and r_4 is (4,5) - cannot broadcast together

try:
    print(np.add(r_2, r_4))
except ValueError as e:
    print(f"r_2 + r_4 error: {e}")

try:
    print(np.add(r_3, r_4))
except ValueError as e:
    print(f"r_3 + r_4 error: {e}")

r_1 + r_4 error: operands could not be broadcast together with shapes (2,) (4,5) 
r_2 + r_4 error: operands could not be broadcast together with shapes (1,2) (4,5) 
r_3 + r_4 error: operands could not be broadcast together with shapes (2,1) (4,5) 


In [23]:
print(np.add(np.array([1]), r_4))

print(np.add(np.array([[1]]), r_4))

print(np.add(np.array([1,1,1,1,1]), r_4))

try:
    print(np.add(np.array([[1], [1]]), r_4))
except ValueError as e:
    print(f"error: {e}")

[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
[[51 77 40 72 72]
 [64 42 80 44 63]
 [51 36 63 21 39]
 [50 67 57 63 35]]
error: operands could not be broadcast together with shapes (2,1) (4,5) 


Broadcasting works by stretching smaller arrays to match the shape of largers ones.

## Rounding

In [ ]:
print(f"r_4:\n{r_4}")
print(f"\nSum of all values: {np.sum(r_4)}")
print(f"\nSum along axis=0 (by column) : \n{np.sum(r_4, axis=0)}")
print(f"\nSum along axis=1 (by row) : \n{np.sum(r_4, axis=1)}")
print(f"\nCumlative sum:\n{np.cumsum(r_4)